import type { Doctor, Specialty } from "./types";

export const SPECIALTIES: Specialty[] = [
  { id: "medecine-generale", label: "Médecine générale", labelAr: "طب عام", emoji: "🩺" },
  { id: "dentiste", label: "Dentiste", labelAr: "طب الأسنان", emoji: "🦷" },
  { id: "cardiologie", label: "Cardiologie", labelAr: "أمراض القلب", emoji: "❤️" },
  { id: "dermatologie", label: "Dermatologie", labelAr: "الأمراض الجلدية", emoji: "🧴" },
  { id: "gynecologie", label: "Gynécologie-Obstétrique", labelAr: "أمراض النساء والتوليد", emoji: "🤰" },
  { id: "pediatrie", label: "Pédiatrie", labelAr: "طب الأطفال", emoji: "🧒" },
  { id: "ophtalmologie", label: "Ophtalmologie", labelAr: "طب العيون", emoji: "👁️" },
  { id: "orl", label: "ORL", labelAr: "أنف أذن حنجرة", emoji: "👂" },
  { id: "psychiatrie", label: "Psychiatrie", labelAr: "الطب النفسي", emoji: "🧠" },
  { id: "orthopedie", label: "Orthopédie", labelAr: "جراحة العظام", emoji: "🦴" },
  { id: "gastro", label: "Gastro-entérologie", labelAr: "أمراض الجهاز الهضمي", emoji: "🫁" },
  { id: "kine", label: "Kinésithérapie", labelAr: "العلاج الطبيعي", emoji: "💪" },
];

export const CITIES: string[] = [
  "Tunis",
  "Ariana",
  "Ben Arous",
  "La Marsa",
  "Sfax",
  "Sousse",
  "Monastir",
  "Nabeul",
  "Bizerte",
  "Gabès",
  "Kairouan",
  "Gafsa",
  "Djerba",
];

export const DOCTORS: Doctor[] = [
  {
    slug: "dr-amine-ben-salah-cardiologie-tunis",
    fullName: "Dr Amine Ben Salah",
    fullNameAr: "د. أمين بن صالح",
    specialty: "Cardiologie",
    specialtyAr: "أمراض القلب",
    city: "Tunis",
    governorate: "Tunis",
    address: "12 Avenue Habib Bourguiba, 1001 Tunis",
    photoSeed: "AB",
    languages: ["Arabe", "Français", "Anglais"],
    cnam: true,
    teleconsultation: true,
    priceTnd: 80,
    rating: 4.9,
    reviewCount: 214,
    bio: "Cardiologue avec 15 ans d'expérience, spécialisé en échocardiographie et en prévention cardiovasculaire.",
    education: [
      "Doctorat en médecine — Faculté de Médecine de Tunis",
      "Spécialité cardiologie — CHU La Rabta",
    ],
    nextAvailability: "Aujourd'hui",
  },
  {
    slug: "dr-ines-trabelsi-dermatologie-la-marsa",
    fullName: "Dr Inès Trabelsi",
    fullNameAr: "د. إيناس الطرابلسي",
    specialty: "Dermatologie",
    specialtyAr: "الأمراض الجلدية",
    city: "La Marsa",
    governorate: "Tunis",
    address: "Résidence Yasmine, Avenue de la Plage, La Marsa",
    photoSeed: "IT",
    languages: ["Arabe", "Français"],
    cnam: true,
    teleconsultation: true,
    priceTnd: 70,
    rating: 4.8,
    reviewCount: 168,
    bio: "Dermatologue et vénérologue, prise en charge de l'acné, du psoriasis et dermatologie esthétique.",
    education: [
      "Doctorat en médecine — Faculté de Médecine de Tunis",
      "Spécialité dermatologie — Hôpital Charles Nicolle",
    ],
    nextAvailability: "Demain",
  },
  {
    slug: "dr-mohamed-gharbi-medecine-generale-sfax",
    fullName: "Dr Mohamed Gharbi",
    fullNameAr: "د. محمد الغربي",
    specialty: "Médecine générale",
    specialtyAr: "طب عام",
    city: "Sfax",
    governorate: "Sfax",
    address: "Route de Tunis Km 2, Sfax",
    photoSeed: "MG",
    languages: ["Arabe", "Français"],
    cnam: true,
    teleconsultation: true,
    priceTnd: 40,
    rating: 4.7,
    reviewCount: 342,
    bio: "Médecin de famille, suivi des maladies chroniques (diabète, hypertension) et médecine préventive.",
    education: ["Doctorat en médecine — Faculté de Médecine de Sfax"],
    nextAvailability: "Aujourd'hui",
  },
  {
    slug: "dr-salma-bouazizi-pediatrie-sousse",
    fullName: "Dr Salma Bouazizi",
    fullNameAr: "د. سلمى البوعزيزي",
    specialty: "Pédiatrie",
    specialtyAr: "طب الأطفال",
    city: "Sousse",
    governorate: "Sousse",
    address: "Avenue Léopold Senghor, Sousse",
    photoSeed: "SB",
    languages: ["Arabe", "Français", "Anglais"],
    cnam: true,
    teleconsultation: true,
    priceTnd: 60,
    rating: 4.9,
    reviewCount: 287,
    bio: "Pédiatre, suivi de croissance, vaccination et consultation nourrisson. Accueil chaleureux pour les enfants.",
    education: [
      "Doctorat en médecine — Faculté de Médecine de Sousse",
      "Spécialité pédiatrie — CHU Farhat Hached",
    ],
    nextAvailability: "Aujourd'hui",
  },
  {
    slug: "dr-karim-jlassi-dentiste-ariana",
    fullName: "Dr Karim Jlassi",
    fullNameAr: "د. كريم الجلاصي",
    specialty: "Dentiste",
    specialtyAr: "طب الأسنان",
    city: "Ariana",
    governorate: "Ariana",
    address: "Rue de l'Environnement, Ariana Ville",
    photoSeed: "KJ",
    languages: ["Arabe", "Français"],
    cnam: false,
    teleconsultation: false,
    priceTnd: 50,
    rating: 4.6,
    reviewCount: 129,
    bio: "Chirurgien-dentiste : soins conservateurs, implantologie et orthodontie adulte.",
    education: ["Doctorat en médecine dentaire — Faculté de Monastir"],
    nextAvailability: "Cette semaine",
  },
  {
    slug: "dr-leila-hammami-gynecologie-tunis",
    fullName: "Dr Leïla Hammami",
    fullNameAr: "د. ليلى الهمامي",
    specialty: "Gynécologie-Obstétrique",
    specialtyAr: "أمراض النساء والتوليد",
    city: "Tunis",
    governorate: "Tunis",
    address: "Immeuble Le Belvédère, Avenue Mohamed V, Tunis",
    photoSeed: "LH",
    languages: ["Arabe", "Français"],
    cnam: true,
    teleconsultation: true,
    priceTnd: 90,
    rating: 4.8,
    reviewCount: 253,
    bio: "Gynécologue-obstétricienne, suivi de grossesse, échographie et santé de la femme.",
    education: [
      "Doctorat en médecine — Faculté de Médecine de Tunis",
      "Spécialité gynécologie-obstétrique — Hôpital Wassila Bourguiba",
    ],
    nextAvailability: "Demain",
  },
  {
    slug: "dr-nizar-mejri-ophtalmologie-monastir",
    fullName: "Dr Nizar Mejri",
    fullNameAr: "د. نزار الماجري",
    specialty: "Ophtalmologie",
    specialtyAr: "طب العيون",
    city: "Monastir",
    governorate: "Monastir",
    address: "Avenue de l'Indépendance, Monastir",
    photoSeed: "NM",
    languages: ["Arabe", "Français", "Anglais"],
    cnam: true,
    teleconsultation: false,
    priceTnd: 70,
    rating: 4.7,
    reviewCount: 96,
    bio: "Ophtalmologue : chirurgie de la cataracte, glaucome et troubles de la réfraction.",
    education: ["Doctorat en médecine — Faculté de Médecine de Monastir"],
    nextAvailability: "Cette semaine",
  },
  {
    slug: "dr-yosra-chaabane-psychiatrie-tunis",
    fullName: "Dr Yosra Chaabane",
    fullNameAr: "د. يسرى الشعبان",
    specialty: "Psychiatrie",
    specialtyAr: "الطب النفسي",
    city: "Tunis",
    governorate: "Tunis",
    address: "Rue du Lac Biwa, Les Berges du Lac, Tunis",
    photoSeed: "YC",
    languages: ["Arabe", "Français", "Anglais"],
    cnam: false,
    teleconsultation: true,
    priceTnd: 100,
    rating: 4.9,
    reviewCount: 142,
    bio: "Psychiatre, prise en charge de l'anxiété, de la dépression et thérapies cognitivo-comportementales. Téléconsultation disponible.",
    education: [
      "Doctorat en médecine — Faculté de Médecine de Tunis",
      "Spécialité psychiatrie — Hôpital Razi",
    ],
    nextAvailability: "Aujourd'hui",
  },
  {
    slug: "dr-hatem-baccouche-orthopedie-sfax",
    fullName: "Dr Hatem Baccouche",
    fullNameAr: "د. حاتم البكوش",
    specialty: "Orthopédie",
    specialtyAr: "جراحة العظام",
    city: "Sfax",
    governorate: "Sfax",
    address: "Avenue Majida Boulila, Sfax",
    photoSeed: "HB",
    languages: ["Arabe", "Français"],
    cnam: true,
    teleconsultation: false,
    priceTnd: 80,
    rating: 4.5,
    reviewCount: 87,
    bio: "Chirurgien orthopédiste et traumatologue : genou, hanche et médecine du sport.",
    education: ["Doctorat en médecine — Faculté de Médecine de Sfax"],
    nextAvailability: "Cette semaine",
  },
  {
    slug: "dr-rim-sassi-orl-nabeul",
    fullName: "Dr Rim Sassi",
    fullNameAr: "د. ريم الساسي",
    specialty: "ORL",
    specialtyAr: "أنف أذن حنجرة",
    city: "Nabeul",
    governorate: "Nabeul",
    address: "Avenue Habib Thameur, Nabeul",
    photoSeed: "RS",
    languages: ["Arabe", "Français"],
    cnam: true,
    teleconsultation: true,
    priceTnd: 60,
    rating: 4.6,
    reviewCount: 74,
    bio: "ORL et chirurgie cervico-faciale : otites, sinusites, troubles de l'audition et du sommeil.",
    education: ["Doctorat en médecine — Faculté de Médecine de Tunis"],
    nextAvailability: "Demain",
  },
  {
    slug: "dr-walid-abidi-gastro-bizerte",
    fullName: "Dr Walid Abidi",
    fullNameAr: "د. وليد العبيدي",
    specialty: "Gastro-entérologie",
    specialtyAr: "أمراض الجهاز الهضمي",
    city: "Bizerte",
    governorate: "Bizerte",
    address: "Rue Ibn Khaldoun, Bizerte",
    photoSeed: "WA",
    languages: ["Arabe", "Français"],
    cnam: true,
    teleconsultation: true,
    priceTnd: 75,
    rating: 4.7,
    reviewCount: 111,
    bio: "Gastro-entérologue : endoscopie digestive, maladies du foie et troubles digestifs.",
    education: ["Doctorat en médecine — Faculté de Médecine de Tunis"],
    nextAvailability: "Cette semaine",
  },
  {
    slug: "mme-asma-ferchichi-kine-sousse",
    fullName: "Asma Ferchichi (Kinésithérapeute)",
    fullNameAr: "أسماء الفرشيشي",
    specialty: "Kinésithérapie",
    specialtyAr: "العلاج الطبيعي",
    city: "Sousse",
    governorate: "Sousse",
    address: "Boulevard du 14 Janvier, Sousse",
    photoSeed: "AF",
    languages: ["Arabe", "Français"],
    cnam: true,
    teleconsultation: false,
    priceTnd: 35,
    rating: 4.8,
    reviewCount: 203,
    bio: "Kinésithérapeute : rééducation post-opératoire, lombalgies et kinésithérapie du sport.",
    education: ["Diplôme d'État — École Supérieure des Sciences de la Santé de Tunis"],
    nextAvailability: "Aujourd'hui",
  },
];

export function findDoctor(slug: string): Doctor | undefined {
  return DOCTORS.find((d) => d.slug === slug);
}

export function searchDoctors(query: string, city: string): Doctor[] {
  const q = query.trim().toLowerCase();
  const c = city.trim().toLowerCase();
  return DOCTORS.filter((d) => {
    const matchesQuery =
      !q ||
      d.fullName.toLowerCase().includes(q) ||
      d.specialty.toLowerCase().includes(q) ||
      d.specialtyAr.includes(query.trim());
    const matchesCity =
      !c || d.city.toLowerCase().includes(c) || d.governorate.toLowerCase().includes(c);
    return matchesQuery && matchesCity;
  });
}
